# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WiUnd4X6rpqToa9nPI_uBM4P93g3nx68
"""

print("🤖 Bienvenido al asistente de PhoneVibe")
print("Escribe 'salir' para terminar.")
print("Puedes preguntar por precios o características de los celulares.\n")


def enviar_mensaje(mensaje):
    mensaje = mensaje.lower()

    if "iphone" in mensaje:
        return "El iPhone 17 tiene un precio de $2.500.000."

    elif "samsung" in mensaje or "a05s" in mensaje:
        return "El Samsung Galaxy A05s tiene un precio de $650.000."

    elif "xiaomi" in mensaje or "redmi" in mensaje:
        return "El Xiaomi Redmi Note 12 Pro 4G tiene un precio de $900.000."

    elif "motorola" in mensaje or "g14" in mensaje:
        return "El Motorola Moto G14 tiene un precio de $800.000."

    elif "más barato" in mensaje or "barato" in mensaje:
        return "El celular más barato es el Samsung Galaxy A05s, con un precio de $650.000."

    elif "más caro" in mensaje or "caro" in mensaje:
        return "El celular más caro es el iPhone 17, con un precio de $2.500.000."

    elif "celulares" in mensaje or "productos" in mensaje:
        return """En PhoneVibe tenemos:
- Samsung Galaxy A05s: $650.000
- iPhone 17: $2.500.000
- Xiaomi Redmi Note 12 Pro 4G: $900.000
- Motorola Moto G14: $800.000"""

    elif "hola" in mensaje:
        return "¡Hola! 👋 Soy el asistente de PhoneVibe. ¿En qué puedo ayudarte?"

    else:
        return "No entendí tu pregunta. Puedes preguntar por nuestros celulares, precios o productos."


while True:
    mensaje = input("Tú: ")

    if mensaje.lower() == "salir":
        print("🤖 Gracias por visitar PhoneVibe. ¡Hasta pronto!")
        break

    respuesta = enviar_mensaje(mensaje)
    print("🤖 PhoneVibe:", respuesta)